integration test refactoring (#1008)

diff --git a/hack/int-test-helper/install-missing-software b/hack/int-test-helper/install-missing-software
--- a/hack/int-test-helper/install-missing-software
+++ b/hack/int-test-helper/install-missing-software
@@ -8,6 +8,8 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
+PROJECT_ROOT="$(realpath $(dirname $0)/../..)"
+
 echo "Run install missing software"
 
 # install bash for the get version command
@@ -79,4 +81,12 @@ then
     echo "ginkgo could not be found"
     echo "Try installing it..."
     go install github.com/onsi/ginkgo/v2/ginkgo@v2.2.0
+fi
+
+if ! command -v ocm &> /dev/null
+then
+    echo "ocm could not be found"
+    echo "Try installing it..."
+    OCM_VERSION=$(NO_PREFIX=true ${PROJECT_ROOT}/hack/extract-module-version.sh github.com/open-component-model/ocm)
+    curl -sSfL https://ocm.software/install.sh | OCM_VERSION=${OCM_VERSION} bash
 fi
